version: 2

sources:
  - name: forma_active
    schema: public   # change ONLY if your raw tables are in another schema
    tables:
      - name: customers
      - name: orders
      - name: order_line_items
      - name: products